### PR TITLE
Adding GitHub repo admin to global CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**
Adding GitHub repo admin to global CODEOWNERS

### CODE REVIEW

**Comment by dslomov** [comment]
friendly ping @buchgr

**Comment by buchgr** [comment]
@dslomov I don't feel responsible for this repo. I believe the release subteam should own this repo.

**Comment by dslomov** [comment]
@philwo @laurentlb @katre @aehlig wdyt?

**Comment by laurentlb** [comment]
I don't know anything about Homebrew.
I can review CLs, as long as they are just updating urls and hashes.

**Comment by philwo** [comment]
@dslomov Sure, sign me up!
@laurentlb Sounds good, usually there isn't much more involved here anyway. :)

**Comment by katre** [comment]
I am in the same boat as @laurentlb: I can approve trivial changes but don't understand the underlying system very deeply.

**Comment by dslomov** [comment]
Adding @philwo and @katre as primary and "secondary" owners - lgty?

**Pull request merged**
