### PR TITLE
migrate bazel to homebrew-core

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/bazelbuild/bazel/pull/10258

Right now bazel release update in homebrew-core is followed pretty closely, moving the tap to core would help consolidating some efforts of making the homebrew installation experience better.

### CODE REVIEW

**Comment by chenrui333** [comment]
ping @philwo 

after this, the issue in #11403 would no longer exist.

**Comment by philwo** [comment]
@chenrui333 Just to make sure - what does this do? 😅 Would it mean that everyone who currently has `bazelbuild/tap/bazel` installed would automatically switch to homebrew-core's `bazel` on the next `brew upgrade`?

**Comment by chenrui333** [comment]
Here is my full test steps (once run `brew upgrade bazel`, it would auto port to `homebrew-core` one)
```
$ git reset --hard 4748cafa89b2290a0ad09c787c5c0e2e9f485ff8
HEAD is now at 4748caf Update to Bazel 3.0.0 (#90)

rchen at rui-mbp in /usr/local/Homebrew/Library/Taps/bazelbuild/homebrew-tap on master
$ brew reinstall bazelbuild/tap/bazel
==> Downloading https://releases.bazel.build/3.0.0/release/bazel-3.0.0-installer-darwin-x86_64.sh
######################################################################## 100.0%
==> Reinstalling bazelbuild/tap/bazel
==> ./bazel-3.0.0-installer-darwin-x86_64.sh --prefix=/private/tmp/bazel-20200527-57284-szptrk
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/bazel/3.0.0: 6 files, 40MB, built in 4 seconds

rchen at rui-mbp in /usr/local/Homebrew/Library/Taps/bazelbuild/homebrew-tap on master
$ git checkout migrate-bazel-to-homebrew-core
Switched to branch 'migrate-bazel-to-homebrew-core'
Your branch is up to date with 'rui/migrate-bazel-to-homebrew-core'.

rchen at rui-mbp in /usr/local/Homebrew/Library/Taps/bazelbuild/homebrew-tap on migrate-bazel-to-homebrew-core
$ rm Formula/ba
bazel.rb     bazelisk.rb

rchen at rui-mbp in /usr/local/Homebrew/Library/Taps/bazelbuild/homebrew-tap on migrate-bazel-to-homebrew-core
$ rm Formula/bazel.rb

rchen at rui-mbp in /usr/local/Homebrew/Library/Taps/bazelbuild/homebrew-tap on migrate-bazel-to-homebrew-core [!]
$ brew upgrade bazel
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (bazelbuild/tap and homebrew/cask).
==> Updated Formulae
bazelbuild/tap/bazel ✔                                                                bazelbuild/tap/bazelisk ✔
==> Updated Casks
hbuilderx                                                                             sitebulb
Warning: Use bazel instead of deprecated bazelbuild/tap/bazel

==> Upgrading 1 outdated package:
bazel 3.0.0 -> 3.2.0
==> Upgrading bazel 3.0.0 -> 3.2.0
==> Downloading https://homebrew.bintray.com/bottles/bazel-3.2.0.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/85097c66f207d8e43021d6932c2bd5c5014dd111ecde4eb6ed26a672a11c23be?response-content-disposition=attachment%3Bfilen
######################################################################## 100.0%
==> Pouring bazel-3.2.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/bazel/3.2.0: 13 files, 26.7MB
Removing: /usr/local/Cellar/bazel/3.0.0... (6 files, 40MB)
Removing: /Users/rchen/Library/Caches/Homebrew/bazel--3.1.0.sh... (37.6MB)
Removing: /Users/rchen/Library/Caches/Homebrew/bazel--3.0.0.sh... (37.4MB)
==> Checking for dependents of upgraded formulae...
==> No dependents found!
```

**Comment by chenrui333** [comment]
There is actually a simple way to keep the homebrew-core formula always up to date. I will file a PR regarding that.

**Comment by philwo** [comment]
Nice! I think that's great. @katre @jin WDYT?

@chenrui333 Do you know how "picky" Homebrew is these days in regards to adding new formulas? Could we add tools from Bazel's ecosystem like `ibazel` and `buildozer` there, too?

If we can get the remaining formulas into homebrew-core, we could remove this entire repo eventually.

**Comment by katre** [comment]
I am very happy to move this into Homebrew core. Even more so if we can get ibazel, bazelisk, etc in.

LGTM.

**Comment by chenrui333** [comment]
bazelisk is [there](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazelisk.rb) too, maybe we can move the other formulae to homebrew-core.

**Comment by jin** [comment]
Got here a little late, but this LGTM! Glad to see the happy path for Homebrew users sorted out. Thank you @chenrui333!

**Pull request merged**
