### PR TITLE
Remove deprecated Homebrew option

### PR DESCRIPTION
**Pull request by jramosf**
See https://stackoverflow.com/a/45163490/1377864 for context.

### CODE REVIEW

**Comment by zoidbergwill** [comment]
I was about to make an MR to do this, so thanks for creating it! Hopefully someone takes a look at it in the near future.

**Comment by Topher-the-Geek** [comment]
Is this going to get merged sometime soon?

**Comment by jramosf** [comment]
Reached via email to one of the maintainers of this repo, in case they missed it.

Cheers,

**Comment by sluongng** [comment]
@philwo Sorry for the ping, but could you please help take a look. This deprecation is giving all MacOS users using this tap a warning on each Homebrew update.

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the bazelbuild/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/bazelbuild/homebrew-tap/Formula/ibazel.rb:26
```

**Review by philwo — APPROVED** [review]
I'm so sorry for not seeing this earlier. Thanks for pinging me. Merging it now!

**Comment by jramosf** [comment]
Confirmed with `0.14.0` the warning is gone from `brew`. Thanks!

**Comment by zoidbergwill** [comment]
Thank you!

**Pull request merged**
