### PR TITLE
Fixing the last command for installing bazel from tap

### PR DESCRIPTION
**Pull request by hmemcpy**
This seems to be the correct way of installing bazel from tap.

### CODE REVIEW

**Comment by hmemcpy** [comment]
Using `brew install bazel` doesn't work for me, it tries to install the old version:
```
$ brew install bazel
Error: bazel 0.17.2 is already installed
To install 0.15.2, first run `brew unlink bazel`
```

I did run `brew uninstall bazel` before using the tap commands. Am I holding it wrong?

**Comment by buchgr** [comment]
Thanks @hmemcpy. Do you happen to run macOS 10.14 mojave?

**Comment by hmemcpy** [comment]
Nope, still High Sierra, but I also happened to ask @ittaiz, and he said it was a known bug somewhere, original command *should* work...

**Comment by buchgr** [comment]
I have so far not been able to reproduce the issue. @philwo was able to reproduce it but after a brew update is no longer able to reproduce it either.

@hmemcpy your error message says that `0.17.2` is already installed - so it seems to have worked after all?

**Comment by hmemcpy** [comment]
@buchgr I was only able to install 0.17.2 after running the full command `brew install bazelbuild/tap/bazel` as the last step, trying to run `brew install bazel` attempts to download 0.15.

I did run `brew update` before, my homebrew is 1.7.6.

**Comment by buchgr** [comment]
So we are both on the same macos and homebrew version. Can you post the full output of the following commands please.

```
brew untap bazelbuild/tap
brew uninstall bazelbuild/tap/bazel
brew uninstall bazel
brew tap bazelbuild/tap
brew tap-pin bazelbuild/tap
brew install bazel
```

**Comment by hmemcpy** [comment]
Same thing, I'm afraid:
```
$ brew untap bazelbuild/tap
brew uninstall bazelbuild/tap/bazel
brew uninstall bazel
brew tap bazelbuild/tap
brew tap-pin bazelbuild/tap
brew install bazel
Untapping bazelbuild/tap...
Untapped 1 formula (35 files, 43.9KB).
Error: No available formula with the name "bazelbuild/tap/bazel"
Please tap it and then try again: brew tap bazelbuild/tap
Uninstalling /usr/local/Cellar/bazel/0.17.2... (5 files, 163.0MB)
Ignoring debase-0.2.2.beta9 because its extensions are not built.  Try: gem pristine debase --version 0.2.2.beta9
Ignoring debase-0.2.2.beta9 because its extensions are not built.  Try: gem pristine debase --version 0.2.2.beta9
Updating Homebrew...
==> Tapping bazelbuild/tap
Cloning into '/usr/local/Homebrew/Library/Taps/bazelbuild/homebrew-tap'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Tapped 1 formula (33 files, 43.7KB).
==> Pinned bazelbuild/tap
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
==> Downloading https://homebrew.bintray.com/bottles/bazel-0.15.2.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/39/390fd161839611a293e225c2dc91a37cab8d8fa7dfd4290cc680beb29c05fa15?__gda__=exp=1538053957~hmac=afeaba05e66157dc5287f6926a46fcee5bc57d27f34c4194c7cdc3b740527506&response-content-disposition=
#####                                                                      7.7%^C
```

**Comment by hmemcpy** [comment]
Also, I accidentally mistyped `brew install bazelbuild`, and got the following output:
```
$ brew install bazelbuild
Updating Homebrew...
Error: No available formula with the name "bazelbuild"
==> Searching for a previously deleted formula (in the last month)...

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
This similarly named formula was found:
bazelbuild/tap/bazel
To install it, run:
  brew install bazelbuild/tap/bazel           <-- offers to install using the full tap path
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by buchgr** [comment]
What's with the changes you made to homebrew where it asks you to 

```
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
```

Did you modify the bazel formula?

**Comment by philwo** [comment]
> Did you modify the bazel formula?

I remember that I also got this message and I definitely didn't manually edit formulas.
I went to /usr/local/Homebrew and ran "git status" but it didn't show any changes.
Of course I should have run "git stash list", but I didn't read the message carefully enough ^^;

Maybe it's related?

**Comment by ittaiz** [comment]
I also had this message (and am seeing the issue). Also don’t remember
manually editing anything

**Pull request merged**
